name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd app
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t flask-app .

    - name: Push Docker image to DockerHub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        docker tag flask-app $DOCKERHUB_USERNAME/flask-app
        docker push $DOCKERHUB_USERNAME/flask-app

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull $DOCKERHUB_USERNAME/flask-app
          docker stop flask-app || true && docker rm flask-app || true
          docker run -d -p 80:5000 --name flask-app $DOCKERHUB_USERNAME/flask-app
